const getters = {
  sidebar: state => state.app.sidebar,
  language: state => state.app.language,
  size: state => state.app.size,
  device: state => state.app.device,
  features: state => state.app.features,
  field_types: state => state.app.field_types,
  format_types: state => state.app.format_types,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permission_routes: state => state.permission.routes,
  errorLogs: state => state.errorLog.logs,
  userProjects: state => state.user.projects,
  userSelectProject: state => state.user.selectProject,
  userSelectEnvironment: state => state.user.selectEnvironment,
  userSelectEnvironments: state => state.user.selectEnvironments,
  userSelectServers: state => state.user.selectServers,
}
export default getters
